export const book = [
  {
    id: 1,
    title: 'If You Tell',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41nIJTI4vXL._SX331_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Gregg Olsen'],
    category: 'Thrillers',
    quantity: 1,
    detail:
      'Harrowing and heartrending, If You Tell is a survivor’s story of absolute evil—and the freedom and justice that Nikki, Sami, and Tori risked their lives to fight for. Sisters forever, victims no more, they found a light in the darkness that made them the resilient women they are today—loving, loved, and moving on.',
  },
  {
    id: 6,
    title: 'The Dancing Girl',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41tcq1XoaML._SX322_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['M.M. Chouinard'],
    category: 'Thrillers',
    quantity: 1,
    detail:
      'When loving wife Jeanine Hammond is found dead in a small leafy town in Massachusetts, newly promoted Detective Jo Fournier is shocked to her core. Why leave her body posed like a ballerina? Why steal her wedding band and nothing else? Hungry for answers, Jo questions Jeanine’s husband, but the heart-breaking pain written on his face threatens to tear open Jo’s old wounds. It’s the same pain she felt when her boyfriend was cruelly shot dead by a gang in their hometown of New Orleans. She couldn’t get justice for him, but she’s determined to get justice for Jeanine’s devastated family.',
  },
  {
    id: 7,
    title: 'The Mountain',
    price: 416,
    thumbnailUrl: 'https://m.media-amazon.com/images/I/41L6UXZ9KeL.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Steven Konkoly'],
    category: 'Thrillers',
    quantity: 1,
    detail:
      'Investigating a missing persons case on Murder Mountain means looking for trouble in a propulsive thriller by the author of The Raid.',
  },
  {
    id: 8,
    title: 'I am Watching You',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41xl+3LOJRL._SX323_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Teresa Driscolln'],
    category: 'Thrillers',
    quantity: 1,
    detail:
      'When Ella Longfield overhears two attractive young men flirting with teenage girls on a train, she thinks nothing of it—until she realises they are fresh out of prison and her maternal instinct is put on high alert. But just as she’s decided to call for help, something stops her. The next day, she wakes up to the news that one of the girls—beautiful, green-eyed Anna Ballard—has disappeared.',
  },
  {
    id: 9,
    title: 'Thin Air',
    price: 416,
    thumbnailUrl: 'https://m.media-amazon.com/images/I/41loP-2eVzL.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Lisa Gray'],
    category: 'Thrillers',
    quantity: 1,
    detail:
      'Private investigator Jessica Shaw is used to getting anonymous tips. But after receiving a photo of a three-year-old kidnapped from Los Angeles twenty-five years ago, Jessica is stunned to recognize the little girl as herself.Eager for answers, Jessica heads to LA’s dark underbelly. When she learns that her biological mother was killed the night she was abducted, Jessica’s determined to solve a case the police have forgotten. Meanwhile, veteran LAPD detective Jason Pryce is in the midst of a gruesome investigation into a murdered college student moonlighting as a prostitute. A chance encounter leads to them crossing paths, but Jessica soon realizes that Pryce is hiding something about her father’s checkered history and her mother’s death.To solve her mother’s murder and her own disappearance, Jessica must dig into the past and find the secrets buried there. But the air gets thinner as she crawls closer to the truth, and it’s getting harder and harder to breathe.',
  },
  {
    id: 10,
    title: 'What Hurts the Most',
    price: 416,
    thumbnailUrl: 'https://m.media-amazon.com/images/I/5158eVzBKcL.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Willow Rose'],
    category: 'Thrillers',
    quantity: 1,
    detail:
      'While her life is going from bad to worse, journalist Mary Mills receives a disturbing phone call from her father. Her brother was arrested, charged with murder.Mary decides to go back to her hometown of Cocoa Beach, Florida, which she left twenty years back and has never visited since.Working with her old friends in from High School, she tracks down the most disturbing and surprising killer this town has ever faced before a shocking conclusion turns everything upside down for them.Determined to solve the murder and to have her brother acquitted, Mary is forced to face demons from her past she never thought she would have to again.',
  },
  {
    id: 11,
    title: 'The Stillness Broken',
    price: 416,
    thumbnailUrl: 'https://m.media-amazon.com/images/I/51Qjj8090gL.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Lawrence Falcetano'],
    category: 'Thrillers',
    quantity: 1,
    detail:
      "The course of his investigation unearths a possible, but uncorroborated connection between his friend and a drug peddling ring. Is his friend dead? Is he running from the law? What mysterious circumstance has caused his friend to fall off the face of the earth?Max wants answers!He embarks on an investigation littered with underworld figures, drug traffickers, and deceitful women. In the course of his pursuit, his life and the lives of his loved ones are threatened, and his bureau chief has ordered him to stop his investigation. All obstacles in keeping Max from discovering his friend's whereabouts.Thus begins an unanticipated battle of wits and survival. Max is now challenged with finding his friend, battling a small army that wants him dead, keeping those close to him out of harm's way, and doing it all without his bureau chief finding out.",
  },
  {
    id: 12,
    title: 'The Accident',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41UhY2DGuYL._SX311_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Natalie Barelli'],
    category: 'Thrillers',
    quantity: 1,
    detail:
      "Katherine knew she’d had too many drinks, but they were only going a short distance. And as Eve pointed out, it was late, there was no traffic anyway...Now, Katherine would give anything to turn back the clock. If anyone ever found out about the accident, it would ruin her life. But no one needs to know because Eve was there too, and she’s going to help make it all go away.Except something's not quite right with Eve, and by the time Katherine realizes that…It’s too late.",
  },
  {
    id: 13,
    title: "A Gentleman's Murder",
    price: 416,
    thumbnailUrl: 'https://m.media-amazon.com/images/I/61T0GuWKfzL.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Christopher Huang'],
    category: 'Thrillers',
    quantity: 1,
    detail:
      "The year is 1924. The streets of St. James ring with jazz as Britain races forward into an age of peace and prosperity. London's back alleys, however, are filled with broken soldiers and still shadowed by the lingering horrors of the Great War.Only a few years removed from the trenches of Flanders himself, Lieutenant Eric Peterkin has just been granted membership in the most prestigious soldiers-only club in London: The Britannia. But when a gentleman's wager ends with a member stabbed to death, the victim's last words echo in the Lieutenant's head: that he would \"soon right a great wrong from the past.\"Eric is certain that one of his fellow members is the murderer: but who? Captain Mortimer Wolf, the soldier's soldier thrice escaped from German custody? Second Lieutenant Oliver Saxon, the brilliant codebreaker? Or Captain Edward Aldershott, the steely club president whose Savile Row suits hide a frightening collision of mustard gas scars?Eric's investigation will draw him far from the marbled halls of the Britannia, to the shadowy remains of a dilapidated war hospital and the heroin dens of Limehouse. And as the facade of gentlemenhood cracks, Eric faces a Matryoshka doll of murder, vice, and secrets pointing not only to the officers of his own club but the very investigator assigned by Scotland Yard.",
  },
  {
    id: 14,
    title: 'Drift',
    price: 416,
    thumbnailUrl: 'https://m.media-amazon.com/images/I/41jKU+tQ1xL.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['L.T. Ryan'],
    category: 'Thrillers',
    quantity: 1,
    detail:
      "Ex-Army criminal investigator Rachel Hatch is a drifter. No home. No commitments. Until her sister's drowning drags her back to the town she left fifteen years ago.Convinced her sister's death was no accident, Hatch partners with the local sheriff, Dalton Savage to uncover the truth. Every answer unlocks another question, and as the investigation begins to unravel, Hatch and Savage find their lives on the line.Hatch is forced to use her special set of skills - forged on the field of combat - to learn the truth about her sister and bring those responsible to justice.The first novel in one of the most highly-anticipated collaborative series this decade, DRIFT is a tightly woven story, with deeply-developed and endearing characters that will have you rooting for them at every turn, set at an exhilarating pace that will keep you turning pages late into the night.",
  },
  {
    id: 14,
    title: 'The Vanishing Half',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41EzNnr4YUL._SX329_BO1,204,203,200_.jpg ',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Brit Bennett'],
    category: 'Fiction',
    quantity: 1,
    detail:
      'Brit Bennett’s The Vanishing Half lives just outside the realm of realism, in that space where a touch of fantasy serves to underscore the strangeness of reality. In her second novel, Bennett invents the tiny Black town of Mallard, La., where the residents pride themselves on their light skin, and identical twins Stella and Desiree Vignes are growing up in the 1950s all too aware of racial violence and oppression. It feels almost inevitable, then, when the girls run away together seeking better opportunities—and soon Stella makes the decision, easy at first and harder with time, to pass as white. Suddenly, she’s gone, leaving a devastated Desiree behind. Bennett weaves a layered and satisfying narrative that shifts through time and multiple characters’ perspectives to trace the impact of a single decision on Stella, her family and the next generation. An eloquent new entry to literature on that most vital of subjects, identity, The Vanishing Half is the novel of the year.',
  },
  {
    id: 14,
    title: 'Shuggie Bain',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41pVfPmXXfL._SX331_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Douglas Stuart'],
    category: 'Fiction',
    quantity: 1,
    detail:
      'Douglas Stuart’s acclaimed debut novel draws heavily on his upbringing in 1980s Glasgow, where, like Stuart did, Hugh “Shuggie” Bain is growing up with an alcoholic mother and facing a culture of homophobia that makes him feel like an outcast. His father and two older siblings have left home, long before he can. Against the backdrop of a city neglected by the government and in decline, Shuggie and Agnes wrestle for control over their lives, often finding themselves swept away by the waves of her addiction. While the setting is bleak, littered with descriptions of quiet indignities—Agnes’ late-night calls to her ex-husband’s taxi company, lingering mugs filled with day-old beer—the guiding light of the novel is the boy’s enduring love for his mother. Stuart writes beautifully observed inner lives for both characters, capturing Shuggie’s devotion to his sometimes vivacious and glamorous mother and the pain that comes from seeing her transformed into a hateful, unpredictable stranger by drink. The novel, a National Book Award finalist and winner of the Booker Prize, is a gut punch.',
  },
  {
    id: 14,
    title: 'The Mirror & the Light',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51ruXud0wVL._SX327_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Hilary Mantel'],
    category: 'Fiction',
    quantity: 1,
    detail:
      'Few novels were as eagerly anticipated this year as The Mirror & The Light, the conclusion to British author Hilary Mantel’s blockbuster Wolf Hall trilogy. Mantel’s evocation of Tudor England and her ear for political drama were just as immersive as ever, and the book climbed to the top of bestseller lists in the U.S. and U.K. In 900 richly detailed pages, The Mirror & The Light lays out the downfall of Thomas Cromwell, consigliere to King Henry VIII and powerbroker of the Reformation. It’s historical fiction, but dazzlingly literary in its ambitions and dramatic in the cut and thrust of its dialogue. Mantel’s Cromwell is a character for the ages—rough-edged yet introspective, with a mind as sharp as an axe. Her Henry, meanwhile, is an apt reminder that self-pitying men with oversized egos enjoyed power long before the present.',
  },
  {
    id: 14,
    title: 'A Children’s Bible',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/510DHM71q7L._SX327_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Lydia Millet'],
    category: 'Fiction',
    quantity: 1,
    detail:
      'On a vacation like no other, a group of families share a lakeside summer home, where the parents care little about what their children are up to. When a catastrophic storm tears through the house, the adults choose to ignore the chaos and turn to the liquor cabinet instead, leaving the kids to seek safety on their own. In the slim and propulsive novel, teenager Evie narrates the group’s struggles in the midst of apocalyptic levels of devastation. Her thoughts on the burgeoning natural disaster capture the dual personalities of a sulking teen, sick of her parents, and a young person forced to grow up too fast. Pulitzer Prize finalist Lydia Millet’s novel, which was a National Book Award finalist, is both an adventure story reminiscent of the classics and a warning tale of a grim future told through the eyes of a generation far too comfortable with catastrophe.',
  },
  {
    id: 14,
    title: 'Homeland Elegies',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51sb1BA3ycL._SX320_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Ayad Akhtar'],
    category: 'Fiction',
    quantity: 1,
    detail:
      'Every so often we are gifted a novel that combines deep intelligence, meticulous prose and something profound to say about the state of our world. In Homeland Elegies, Pulitzer Prize winner Ayad Akhtar gives readers just that in the story of a man very much like himself, who shares his name and was born to Pakistani immigrants in the American Midwest as Akhtar was. From the opening chapters when the fictional Ayad’s father treats Donald Trump for a heart condition in the 1990s, it’s clear we are in a world that is recognizable but not necessarily real. That’s all part of Akhtar’s point: his project uses fiction as a filter through which to tell an essential story about a man facing the turmoil of American life after 9/11 and his family’s attendant struggle to define itself. It’s a delicate balancing act between what’s real and what may not be, yet in Akhtar’s brilliant book the complexities of the American Dream have never been so naked.',
  },
  {
    id: 14,
    title: 'I Hold a Wolf by the Ears',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41Ka2o+-ojL._SX324_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Laura van den Berg'],
    category: 'Fiction',
    quantity: 1,
    detail:
      'The 11 stories that comprise Laura van den Berg’s beautiful and bold collection feature a cast of contemplative women navigating situations that are strange, sad and unsettling. Among them are the “grief freelancer” who brings in extra income by impersonating the dead, the wife who is unknowingly being drugged by her husband with sedative-spiked seltzer and the daughter who accompanies her ailing mother on a bittersweet final tour of Italy. The characters in these narratives are each broken in different ways, but they all quietly grapple with life’s greatest questions—the meaning of loneliness and loss, the durability of love. I Hold a Wolf by the Ears is short fiction at its finest: van den Berg captures the cruelest of traumas on one page, then supplies a healing dose of humor on the next.',
  },
  {
    id: 14,
    title: 'A Burning',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41-edXuDruL._SX300_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Megha Majumdar'],
    category: 'Fiction',
    quantity: 1,
    detail:
      'After witnessing a terrorist attack, Jivan, a poor Muslim woman living in the slums of Kolkata, makes a comment on Facebook criticizing her government’s response to the tragic event. It’s an action with terrible consequences, as she’s taken into custody and accused of aiding the attackers. In her exquisitely plotted debut novel, Megha Majumdar writes with absorbing urgency as she details Jivan’s plight. Beyond Jivan, Majumdar introduces two key perspectives: the protagonist’s former gym teacher, PT Sir, who has ties to the right-wing political party that seeks to seal her fate, and Lovely, an outcast with dreams of being an actor and the only person who can prove Jivan’s innocence. In moving between their three voices, Majumdar reveals the intersections of their ambitions and fears, coalescing into an unnerving investigation of corruption, class and tragedy.',
  },
  {
    id: 14,
    title: 'Deacon King Kong',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51Qi4HmgwLL._SX329_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['James McBride'],
    category: 'Fiction',
    quantity: 1,
    detail:
      'It’s September 1969 when Sportcoat, the grumpy old deacon of a church in the Causeway Houses project in Brooklyn, shoots local drug dealer Deems in the face. The whole neighborhood is buzzing with the news: Sportcoat pulled a .38 from his pocket and blew the ear off of the boy he used to coach in baseball. Why on earth would he do such a thing? Even the deacon himself doesn’t seem to know. National Book Award-winning author James McBride unveils the answer in this story of comedy and compassion, which pays loving attention to a wide cast of characters. McBride describes their world in densely packed, rhythmic specificities, fixating on the community’s rich local history and the voices that populate it.',
  },
  {
    id: 14,
    title: 'Where the Wild Ladies Are',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41SejyLRyuL._SX332_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Aoko Matsuda'],
    category: 'Fiction',
    quantity: 1,
    detail:
      'In Where the Wild Ladies Are, Japanese author Aoko Matsuda guides readers through supernatural events and introduces them to otherworldly characters as if they were completely ordinary. That understated and witty touch is what makes this short story collection, translated to English by Polly Barton, so special. Matsuda updates traditional Japanese ghost stories for the contemporary era, giving agency to previously voiceless female characters and playfully breaking down gender roles and stereotypes still so pervasive in Japanese culture today. A translator herself, Matsuda knows how to play with language, infusing her narrators with memorable idiosyncrasies. While each chapter is its own contained short story, some interlink. The result is a reimagining of traditional tales as part of a broader narrative about women and power.',
  },
  {
    id: 14,
    title: 'Breasts and Eggs',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/31PvgjUtQkL._SX323_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Mieko Kawakami'],
    category: 'Fiction',
    quantity: 1,
    detail:
      'In her first novel published in English, Japanese author Mieko Kawakami follows three women and their relationships with their changing bodies. There’s 30-year-old Natsu, her older sister Makiko and Makiko’s daughter Midoriko. The first half of Breasts and Eggs, translated by Sam Bett and David Boyd, centers on Makiko’s quest to plan a breast enhancement procedure, and Midoriko’s recent refusal to speak to her. Their interactions are relayed through the dry voice of Natsu in scenes filled with blunt and witty dialogue. Then, Kawakami shifts the story forward, picking up 10 years later and focusing on Natsu as she is single but considering motherhood. While Natsu was measured and judgmental in narrating the story of her sister’s obsession with perfecting her image, she is now uncertain and confused by her own fears about aging. In describing these anxieties, Kawakami takes a stirring look at the expectations put on women by the world and by themselves.',
  },
  {
    id: 3,
    title: 'Harrow The Ninth',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51eBlhyIrKL._SX322_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Tamsyn Muir'],
    category: 'Sci-fi',
    quantity: 1,
    detail:
      'Harrow The Ninth is another one of the best science fiction books. If you’ve not read the very first book of Muir’s Locked Tomb trilogy, Gideon the Ninth, read it first. At that stage, you would likely not need any motivation to dive into the second book, Harrow the Ninth, which picks up right where the first book left off, whilst managing to outdo its precedent in baffling puzzles, imaginative sci-fi horror, and the particular brand of pulsing elegance and wit of Muir.',
  },
  {
    id: 3,
    title: 'Axiom’s End ',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51jLXb46NVL._SX327_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Lindsay Ellis'],
    category: 'Sci-fi',
    quantity: 1,
    detail:
      'Next, one of the great sci-fi books 2020 is Axiom’s End. In an alternate version from 2007, this groundbreaking novel from video essayist Lindsay Ellis images an alien first contact case, capturing both the political and cultural atmosphere of the period while exploring what it really implies to be human or alien. It will be, undoubtedly, one of the best sci-fi books you’ve ever read.',
  },
  {
    id: 3,
    title: 'A Beautifully Foolish Endeavor ',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51qBkinEVYL._SX329_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Hank Green'],
    category: 'Sci-fi',
    quantity: 1,
    detail:
      'Of the new fantasy books, this is another sequel. Before you jump in, you will probably would like to look for Green’s first story – An Absolutely Remarkable Thing. Both best-selling sci-fi books explore the backlash that occurs when April May confronts a mysterious, alien statue while also discussing how social media and celebrity can affect how we communicate with and view the world. These best sci-fi books encompass other attention-grabbing aspects as well.',
  },
  {
    id: 3,
    title: 'To Sleep In A Sea Of Stars',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51LV5uH7NmL._SX327_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Christopher Paolini'],
    category: 'Sci-fi',
    quantity: 1,
    detail:
      'Paolini’s first narrative goes on from dragons to distant space and from YA narratives to a more mature community after his famous Inheritance Cycle. Xenobiologist Kira Navárez meets a mysterious alien relic, and things spiral rapidly into a war that could determine the destiny of the interstellar society of mankind. Of the top science fiction books, it’s a great book to hide in during the vacations, at almost 900 pages.',
  },
  {
    id: 3,
    title: 'The City We Became',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51NQo5T9yQL._SX332_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['N.K. Jemisin'],
    category: 'Sci-fi',
    quantity: 1,
    detail:
      'Jemisin is renowned for her spectacular Broken Earth trilogy – one of the great sci-fi books. The City We Became reinvents New York City as a living, breathing creature, characterized by a diverse group of individuals from around the five boroughs as they battle to save the city from an unearthly enemy. The City We Became, one of the best sci-fi fantasy books 2020, is novel-sized spinoff of a previous short story by Jemisin.',
  },
  {
    id: 3,
    title: 'The Hidden Girl And Other Stories',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41xLleztkXL._SX329_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Ken Liu'],
    category: 'Sci-fi',
    quantity: 1,
    detail:
      'Liu, starting from his first collection, The Paper Menagerie, already has become one of the biggest names in sci-fi and fantasy short stories. His new offering, The Hidden Girl and Other Stories, presents 17 new stories looking at artificial intelligence, classical mythology, and more in a new way. The Hidden Girl And Other Stories, among the other famous science fiction books, is best recent sci-fi books.',
  },
  {
    id: 3,
    title: 'Network Effect ',
    price: 416,
    thumbnailUrl: 'https://m.media-amazon.com/images/I/41spd48rBaL.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Martha Wells'],
    category: 'Sci-fi',
    quantity: 1,
    detail:
      'one of the top fantasy sci-fi books. A conscience, technologically smart killing machine, Murderbot is one of the best science fiction heroes in recent memory. Murderbot was already the star of the novels in Wells’ Murderbot Diaries, but Network Effect, best sci-fi books, one of the offers the cynical TV-marathoning robot who only wants a break a genuine comprehensive novel. Best of all, it’s a collection, so the first few novels you won’t read, but you possibly should, seeing as they’re just as amazing.',
  },
  {
    id: 3,
    title: 'Subcutanean',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41vufoPam2L._SX322_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Aaron A. Reed'],
    category: 'Sci-fi',
    quantity: 1,
    detail:
      'The most special book of 2020, or maybe ever, essentially, could be ‘Subcutanean’ – one of the top sci-fi books. With each print of the book featuring its own distinctive text, Reed, a renowned author for constructing the popular sci-fi books, explains it as a ‘permutational novel.’ Some variations will be major, others slight, from copy to copy, even though the overall story remains essentially pretty similar.',
  },
  {
    id: 3,
    title: 'The Ballad Of Snakes And Songbirds',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/516xnRU0DvL._SX325_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Suzanne Collins'],
    category: 'Sci-fi',
    quantity: 1,
    detail:
      'The return to the world of Panem’s The Hunger Games arrives just about a full decade after Mockingjay’s publication. But The Ballad of Snakes and Songbirds, one of the top sci-fi books of all time, is a prequel that reflects on the rising of dominance of the future President Snow, and the political and social powers that forged the Hunger Games, rather than another action-packed plunge into the field.',
  },
  {
    id: 3,
    title: 'Shorefall',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51iiK4c-6gL._SX329_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Robert Jackson Bennett'],
    category: 'Sci-fi',
    quantity: 1,
    detail:
      'Functionally, Shorefall is one of the best fantasy books, but it is still included because it’s set in a mystical world that’s far more focused on computer coding and AI than on swords and elves. In a city full of mystical machines and enhancements, it’s a somewhat cyberpunk take on the style. In the city of Tevanne, virtually anything is a coded AI of some kind, and as they govern the city, huge, towering megacorporations spar with each other. Before you move to Shorefall, begin with Foundryside, the first book in the sequence, which ratchets things up another level. Of the best new sci-fi books, Shorefall maintains its position of being one of the sci-fi books to read.',
  },
  {
    id: 4,
    title: 'The Valmiki Ramayana',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51WtAqrd4QL._SX331_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Debroy Bibek'],
    category: 'Mythological',
    quantity: 1,
    detail:
      'Ramayana still lives in the hearts of Indians, and it will never cease to be so. The Valmiki Ramayana by Debroy Bibek tells the tale of the victory of good over evil. This book narrates the entire story of the prince of Ayodhya, Prabhu Shri Ram, recounting his exile and the battle with the demon king Ravana.',
  },
  {
    id: 4,
    title: 'Mahabharata',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51FcDWlv4XL._SX309_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Purnaprajna Das'],
    category: 'Mythological',
    quantity: 1,
    detail:
      'Mahabharata is another major epic of Indian mythology. It is also the longest epic in Sanskrit. This concise rendition of Purnaprajna Das of the Mahabharata would be a great read for everyone, beginners and experienced readers alike. So many different stories run parallel, with thousands of characters.',
  },
  {
    id: 4,
    title: 'The Shiva Trilogy',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51HkmTELu2L._SX332_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Amish Tripathi'],
    category: 'Mythological',
    quantity: 1,
    detail:
      'These books are a journey of Shiva who becomes Neelkanth and tries to save the Suryavanshi dynasty from various attacks from the Chandravanshis and the Nagas. Even if you are a non-fiction reader, this book will interest you as the author has skillfully crafted the amalgamation of mythology and fiction.',
  },
  {
    id: 4,
    title: 'The Palace of Illusions',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/512BeZfOAdL._SX326_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Chitra Banerjee Divakaruni'],
    category: 'Mythological',
    quantity: 1,
    detail:
      'Narrated by Draupadi, the legendary wife of the Pandavas, this novel offers a new interpretation of the Indian epic Mahabharata. This novel focuses on her life, beginning from her birth from fire to the way her husbands were deceived into losing their entire kingdom. Draupadi, despite the humiliation, does not leave the side of her husbands.',
  },
  {
    id: 4,
    title: 'The Siva Purana',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51H6ab406TL._SX328_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['J.L. Shastri'],
    category: 'Mythological',
    quantity: 1,
    detail:
      "Puranas are a class of literature that includes religion, philosophy, history, sociology, politics, and other subjects. The Siva Purana by J.L. Shastri is a narration of Lord Shiva's and Maa Parvati's story. Originally written by Romaharshana, the Shiv Purana included over 100,000 verses. This rendition is a concise version of that.",
  },
  {
    id: 4,
    title: 'Yuganta: The End of an Epoch',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51GxGZz-32L._SX326_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Irawati Karve'],
    category: 'Mythological',
    quantity: 1,
    detail:
      "Yuganta is a unique book as it presents the Indian mythological tales and heroes from today's perspective. It talks about their fears, hopes, and make them sound like a regular human of today's world. This gives contemporary readers a great way to relate to the characters and stories better.",
  },
  {
    id: 4,
    title: 'Scion of Ikshvaku',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51ApvbRG8bL._SX323_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Amish Tripathi'],
    category: 'Mythological',
    quantity: 1,
    detail:
      'The Scion of Ikshvaku is another mythological fiction by Amish Tripathi. In this book, he has narrated a story of Ram Rajya (a perfect land), with its ramifications. The story is based in 3400 BC when Ayodhya is undermined by divisions. Prince Ram emerges as an unlikely hero to save the people of Ayodhya from the demon king Ravana.',
  },
  {
    id: 4,
    title: 'Vanara: The Legend of Baali, Sugreeva and Tara',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/5158trOXqKL._SX310_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Anand Neelakantan'],
    category: 'Mythological',
    quantity: 1,
    detail:
      'Baali and Sugreeva had a life full of hardships from the very beginning. They were slaves and were often mocked as monkey men. Baali was determined to change the way their lives were, and he, along with Sugreeva, built a country with the capital city of Kishkindha. This country had no discrimination.',
  },
  {
    id: 4,
    title: 'Ganga: The Constant Goddess',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51aOzzHwsGL._SX322_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Anuja Chandramouli'],
    category: 'Mythological',
    quantity: 1,
    detail:
      'Goddess Ganga has been revered as the epitome of beauty and purity in this culture since time immemorial. She is believed to be the liquid manifestation of Shakti and nurturer of the three worlds. She is a constant Goddess, renowned as a caring mother, a devoted daughter, and a passionate lover.',
  },
  {
    id: 4,
    title: 'Karnas Wife: The Outcasts Queen',
    price: 416,
    thumbnailUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51KaDVFb0qL._SX322_BO1,204,203,200_.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Kavita Kane'],
    category: 'Mythological',
    quantity: 1,
    detail:
      "Karna is one of the most important characters of Mahabharata. Uruvi, his wife, is a Kshatriya princess who witnesses the roller coaster ride of Karna's fate. She knew that marrying Karna would bring many social implications, but she faced all the challenges. She counseled and guided him throughout Mahabharata.",
  },
  {
    id: 5,
    title: 'Ivanhoe',
    price: 416,
    thumbnailUrl:
      '//prodimage.images-bn.com/pimages/9781593082468_p0_v1_s550x406.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Walter Scott'],
    category: 'Adventures',
    quantity: 1,
    detail: 'ds',
  },
  {
    id: 5,
    title: 'The Three Musketeers',
    price: 416,
    thumbnailUrl:
      '//prodimage.images-bn.com/pimages/9781593081485_p0_v1_s550x406.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Alexandre Dumas'],
    category: 'Adventures',
    quantity: 1,
    detail: 'ds',
  },
  {
    id: 5,
    title: '20,000 Leagues Under the Sea',
    price: 416,
    thumbnailUrl:
      '//prodimage.images-bn.com/pimages/9781593083021_p0_v3_s550x406.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Jules Verne'],
    category: 'Adventures',
    quantity: 1,
    detail: 'ds',
  },
  {
    id: 5,
    title: 'Treasure Island',
    price: 416,
    thumbnailUrl:
      '//prodimage.images-bn.com/pimages/9781593082475_p0_v4_s550x406.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Robert Louis Stevenson'],
    category: 'Adventures',
    quantity: 1,
    detail: 'ds',
  },
  {
    id: 5,
    title: 'King Solomon’s Mines',
    price: 416,
    thumbnailUrl:
      '//prodimage.images-bn.com/pimages/9781593082758_p0_v1_s550x406.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['H. Rider Haggard'],
    category: 'Adventures',
    quantity: 1,
    detail: 'ds',
  },
  {
    id: 5,
    title: 'Kim',
    price: 416,
    thumbnailUrl:
      '//prodimage.images-bn.com/pimages/9781593081928_p0_v4_s550x406.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Rudyard Kipling'],
    category: 'Adventures',
    quantity: 1,
    detail: 'ds',
  },
  {
    id: 5,
    title: 'The Call of the Wild',
    price: 416,
    thumbnailUrl:
      '//prodimage.images-bn.com/pimages/9781593082000_p0_v1_s550x406.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Jack London'],
    category: 'Adventures',
    quantity: 1,
    detail: 'ds',
  },
  {
    id: 5,
    title: 'The Scarlet Pimpernel',
    price: 416,
    thumbnailUrl:
      '//prodimage.images-bn.com/pimages/9781593082345_p0_v4_s550x406.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Baroness Orczy'],
    category: 'Adventures',
    quantity: 1,
    detail: 'ds',
  },
  {
    id: 5,
    title: 'Tarzan of the Apes',
    price: 416,
    thumbnailUrl:
      '//prodimage.images-bn.com/pimages/9781593082277_p0_v1_s550x406.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Edgar Rice Burroughs'],
    category: 'Adventures',
    quantity: 1,
    detail: 'ds',
  },
  {
    id: 5,
    title: 'Captain Blood',
    price: 416,
    thumbnailUrl:
      '//prodimage.images-bn.com/pimages/9780142180105_p0_v1_s550x406.jpg',
    comments: 'Good Book',
    rating: 4.0,
    authors: ['Rafael Sabatini'],
    category: 'Adventures',
    quantity: 1,
    detail: 'ds',
  },
];
